module.exports = [
  {
    id: 'abob',
    image_url: 'American_Bobtail',
    name: 'American Bobtail',
    description: 'American Bobtails are loving and incredibly intelligent cats possessing a distinctive wild appearance. They are extremely interactive cats that bond with their human family with great devotion.',
    temperament: 'Intelligent, Interactive, Lively, Playful, Sensitive',
    origin: 'United States',
    life_span: '11 - 15',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 5,
    health_issues: 1,
    social_needs: 3,
    stranger_friendly: 3
  },
  {
    id: 'abys',
    image_url: 'Abyssinian',
    name: 'Abyssinian',
    description: 'The Abyssinian is easy to care for, and a joy to have in your home. They’re affectionate cats and love both people and other animals.',
    temperament: 'Active, Energetic, Independent, Intelligent, Gentle',
    origin: 'Egypt',
    life_span: '14 - 15',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 3,
    grooming: 1,
    intelligence: 5,
    health_issues: 2,
    social_needs: 5,
    stranger_friendly: 5
  },
  {
    id: 'acur',
    image_url: 'American_Curl',
    name: 'American Curl',
    description: 'Distinguished by truly unique ears that curl back in a graceful arc, offering an alert, perky, happily surprised expression, they cause people to break out into a big smile when viewing their first Curl. Curls are very people-oriented, faithful, affectionate soulmates, adjusting remarkably fast to other pets, children, and new situations.',
    temperament: 'Affectionate, Curious, Intelligent, Interactive, Lively, Playful, Social',      
    origin: 'United States',
    life_span: '12 - 16',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 2,
    intelligence: 3,
    health_issues: 1,
    social_needs: 3,
    stranger_friendly: 3
  },
  {
    id: 'aege',
    image_url: 'Aegean',
    name: 'Aegean',
    description: 'Native to the Greek islands known as the Cyclades in the Aegean Sea, these are natural cats, meaning they developed without humans getting involved in their breeding. As a breed, Aegean Cats are rare, although they are numerous on their home islands. They are generally friendly toward people and can be excellent cats for families with children.',
    temperament: 'Affectionate, Social, Intelligent, Playful, Active',
    origin: 'Greece',
    life_span: '9 - 12',
    adaptability: 5,
    affection_level: 4,
    child_friendly: 4,
    grooming: 3,
    intelligence: 3,
    health_issues: 1,
    social_needs: 4,
    stranger_friendly: 4
  },
  {
    id: 'amau',
    image_url: 'Arabian_Mau',
    name: 'Arabian Mau',
    description: 'Arabian Mau cats are social and energetic. Due to their energy levels, these cats do best in homes where their owners will be able to provide them with plenty of playtime, attention and interaction from their owners. These kitties are friendly, intelligent, and adaptable, and will even get along well with other pets and children.',
    temperament: 'Affectionate, Agile, Curious, Independent, Playful, Loyal',
    origin: 'United Arab Emirates',
    life_span: '12 - 14',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 3,
    health_issues: 1,
    social_needs: 3,
    stranger_friendly: 3
  },
  {
    id: 'amis',
    image_url: 'Australian_Mist',
    name: 'Australian Mist',
    description: 'The Australian Mist thrives on human companionship. Tolerant of even the youngest of children, these friendly felines enjoy playing games and being part of the hustle and bustle of a busy household. They make entertaining companions for people of all ages, and are happy to remain indoors between dusk and dawn or to be wholly indoor pets.',
    temperament: 'Lively, Social, Fun-loving, Relaxed, Affectionate',
    origin: 'Australia',
    life_span: '12 - 16',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 3,
    intelligence: 4,
    health_issues: 1,
    social_needs: 4,
    stranger_friendly: 4
  },
  {
    id: 'asho',
    image_url: 'American_Shorthair',
    name: 'American Shorthair',
    description: 'The American Shorthair is known for its longevity, robust health, good looks, sweet personality, and amiability with children, dogs, and other pets.',
    temperament: 'Active, Curious, Easy Going, Playful, Calm',
    origin: 'United States',
    life_span: '15 - 17',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 3,
    health_issues: 3,
    social_needs: 4,
    stranger_friendly: 3
  },
  {
    id: 'awir',
    image_url: 'American_Wirehair',
    name: 'American Wirehair',
    description: 'The American Wirehair tends to be a calm and tolerant cat who takes life as it comes. His favorite hobby is bird-watching from a sunny windowsill, and his hunting ability will stand you in good stead if insects enter the house.',
    temperament: 'Affectionate, Curious, Gentle, Intelligent, Interactive, Lively, Loyal, Playful, Sensible, Social',
    origin: 'United States',
    life_span: '14 - 18',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 3,
    health_issues: 3,
    social_needs: 3,
    stranger_friendly: 3
  },
  {
    id: 'bali',
    image_url: 'Balinese',
    name: 'Balinese',
    description: 'Balinese are curious, outgoing, intelligent cats with excellent communication skills. They are known for their chatty personalities and are always eager to tell you their views on life, love, and what you’ve served them for dinner. ',
    temperament: 'Affectionate, Intelligent, Playful',
    origin: 'United States',
    life_span: '10 - 15',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 3,
    intelligence: 5,
    health_issues: 3,
    social_needs: 5,
    stranger_friendly: 5
  },
  {
    id: 'bamb',
    image_url: 'Bambino',
    name: 'Bambino',
    description: 'The Bambino is a breed of cat that was created as a cross between the Sphynx and the Munchkin breeds. The Bambino cat has short legs, large upright ears, and is usually hairless. They love to be handled and cuddled up on the laps of their family members.',
    temperament: 'Affectionate, Lively, Friendly, Intelligent',
    origin: 'United States',
    life_span: '12 - 14',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 5,
    health_issues: 1,
    social_needs: 3,
    stranger_friendly: 3
  },
  {
    id: 'beng',
    image_url: 'Bengal',
    name: 'Bengal',
    description: "Bengals are a lot of fun to live with, but they're definitely not the cat for everyone, or for first-time cat owners. Extremely intelligent, curious and active, they demand a lot of interaction and woe betide the owner who doesn't provide it.",
    temperament: 'Alert, Agile, Energetic, Demanding, Intelligent',
    origin: 'United States',
    life_span: '12 - 15',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 5,
    health_issues: 3,
    social_needs: 5,
    stranger_friendly: 3
  },
  {
    id: 'birm',
    image_url: 'Birman',
    name: 'Birman',
    description: 'The Birman is a docile, quiet cat who loves people and will follow them from room to room. Expect the Birman to want to be involved in what you’re doing. He communicates in a soft voice, mainly to remind you that perhaps it’s time for dinner or maybe for a nice cuddle on the sofa. He enjoys being held and will relax in your arms like a furry baby.',
    temperament: 'Affectionate, Active, Gentle, Social',
    origin: 'France',
    life_span: '14 - 15',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 2,
    intelligence: 3,
    health_issues: 1,
    social_needs: 4,
    stranger_friendly: 3
  },
  {
    id: 'bomb',
    image_url: 'Bombay',
    name: 'Bombay',
    description: "The the golden eyes and the shiny black coa of the Bopmbay is absolutely striking. Likely to bond most with one family member, the Bombay will follow you from room to room and will almost always have something to say about what you are doing, loving attention and to be carried around, often on his caregiver's shoulder.",
    temperament: 'Affectionate, Dependent, Gentle, Intelligent, Playful',
    origin: 'United States',
    life_span: '12 - 16',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 5,
    health_issues: 3,
    social_needs: 4,
    stranger_friendly: 4
  },
  {
    id: 'bsho',
    image_url: 'British_Shorthair',
    name: 'British Shorthair',
    description: "The British Shorthair is a very pleasant cat to have as a companion, ans is easy going and placid. The British is a fiercely loyal, loving cat and will attach herself to every one of her family members. While loving to play, she doesn't need hourly attention. If she is in the mood to play, she will find someone and bring a toy to that person. The British also plays well by herself, and thus is a good companion for single people.",
    temperament: 'Affectionate, Easy Going, Gentle, Loyal, Patient, calm',
    origin: 'United Kingdom',
    life_span: '12 - 17',
    adaptability: 5,
    affection_level: 4,
    child_friendly: 4,
    grooming: 2,
    intelligence: 3,
    health_issues: 2,
    social_needs: 3,
    stranger_friendly: 2
  },
  {
    id: 'bslo',
    image_url: 'British_Longhair',
    name: 'British Longhair',
    description: 'The British Longhair is a very laid-back relaxed cat, often perceived to be very independent although they will enjoy the company of an equally relaxed and likeminded cat. They are an affectionate breed, but very much on their own terms and tend to prefer to choose to come and sit with their owners rather than being picked up.',
    temperament: 'Affectionate, Easy Going, Independent, Intelligent, Loyal, Social',
    origin: 'United Kingdom',
    life_span: '12 - 14',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 5,
    intelligence: 5,
    health_issues: 1,
    social_needs: 3,
    stranger_friendly: 4
  },
  {
    id: 'bure',
    image_url: 'Burmese',
    name: 'Burmese',
    description: 'Burmese love being with people, playing with them, and keeping them entertained. They crave close physical contact and abhor an empty lap. They will follow their humans from room to room, and sleep in bed with them, preferably under the covers, cuddled as close as possible. At play, they will turn around to see if their human is watching and being entertained by their crazy antics.',
    temperament: 'Curious, Intelligent, Gentle, Social, Interactive, Playful, Lively',
    origin: 'Burma',
    life_span: '15 - 16',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 5,
    health_issues: 3,
    social_needs: 5,
    stranger_friendly: 5
  },
  {
    id: 'buri',
    image_url: 'Burmilla',
    name: 'Burmilla',
    description: 'The Burmilla is a fairly placid cat. She tends to be an easy cat to get along with, requiring minimal care. The Burmilla is affectionate and sweet and makes a good companion, the Burmilla is an ideal companion to while away a lonely evening. Loyal, devoted, and affectionate, this cat will stay by its owner, always keeping them company.',
    temperament: 'Easy Going, Friendly, Intelligent, Lively, Playful, Social',
    origin: 'United Kingdom',
    life_span: '10 - 15',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 3,
    intelligence: 3,
    health_issues: 3,
    social_needs: 4,
    stranger_friendly: 3
  },
  {
    id: 'char',
    image_url: 'Chartreux',
    name: 'Chartreux',
    description: 'The Chartreux is generally silent but communicative. Short play sessions, mixed with naps and meals are their perfect day. Whilst appreciating any attention you give them, they are not demanding, content instead to follow you around devotedly, sleep on your bed and snuggle with you if you’re not feeling well.',
    temperament: 'Affectionate, Loyal, Intelligent, Social, Lively, Playful',
    origin: 'France',
    life_span: '12 - 15',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 4,
    health_issues: 2,
    social_needs: 5,
    stranger_friendly: 5
  },
  {
    id: 'chau',
    image_url: 'Chausie',
    name: 'Chausie',
    description: 'For those owners who desire a feline capable of evoking the great outdoors, the strikingly beautiful Chausie retains a bit of the wild in its appearance but has the house manners of our friendly, familiar moggies. Very playful, this cat needs a large amount of space to be able to fully embrace its hunting instincts.',
    temperament: 'Affectionate, Intelligent, Playful, Social',
    origin: 'Egypt',
    life_span: '12 - 14',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 3,
    intelligence: 5,
    health_issues: 1,
    social_needs: 3,
    stranger_friendly: 4
  },
  {
    id: 'chee',
    image_url: 'Cheetoh',
    name: 'Cheetoh',
    description: 'The Cheetoh has a super affectionate nature and real love for their human companions; they are intelligent with the ability to learn quickly. You can expect that a Cheetoh will be a fun-loving kitty who enjoys playing, running, and jumping through every room in your house.', 
    temperament: 'Affectionate, Gentle, Intelligent, Social',
    origin: 'United States',
    life_span: '12 - 14',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 5,
    health_issues: 1,
    social_needs: 3,
    stranger_friendly: 4
  },
  {
    id: 'crex',
    image_url: 'Cornish_Rex',
    name: 'Cornish Rex',
    description: 'This is a confident cat who loves people and will follow them around, waiting for any opportunity to sit in a lap or give a kiss. He enjoys being handled, making it easy to take him to the veterinarian or train him for therapy work. The Cornish Rex stay in kitten mode most of their lives and well into their senior years. ',
    temperament: 'Affectionate, Intelligent, Active, Curious, Playful',
    origin: 'United Kingdom',
    life_span: '11 - 14',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 5,
    health_issues: 2,
    social_needs: 5,
    stranger_friendly: 3
  },
  {
    id: 'csho',
    image_url: 'Colorpoint_Shorthair',
    name: 'Colorpoint Shorthair',
    description: 'Colorpoint Shorthairs are an affectionate breed, devoted and loyal to their people. Sensitive to their owner’s moods, Colorpoints are more than happy to sit at your side or on your lap and purr words of encouragement on a bad day. They will constantly seek out your lap whenever it is open and in the moments when your lap is preoccupied they will stretch out in sunny spots on the ground.',
    temperament: 'Affectionate, Intelligent, Playful, Social',
    origin: 'United States',
    life_span: '12 - 16',
    adaptability: 3,
    affection_level: 4,
    child_friendly: 4,
    grooming: 2,
    intelligence: 5,
    health_issues: 2,
    social_needs: 4,
    stranger_friendly: 2
  },
  {
    id: 'cspa',
    image_url: 'California_Spangled',
    name: 'California Spangled',
    description: 'Perhaps the only thing about the California spangled cat that isn’t wild-like is its personality. Known to be affectionate, gentle and sociable, this breed enjoys spending a great deal of time with its owners. They are very playful, often choosing to perch in high locations and show off their acrobatic skills.',
    temperament: 'Affectionate, Curious, Intelligent, Loyal, Social',
    origin: 'United States',
    life_span: '10 - 14',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 5,
    health_issues: 1,
    social_needs: 3,
    stranger_friendly: 4
  },
  {
    id: 'ctif',
    image_url: 'Chantilly_Tiffany',
    name: 'Chantilly Tiffany',
    description: "The Chantilly is a devoted companion and prefers company to being left alone. While the Chantilly is not demanding, she will 'chirp' and 'talk' as if having a conversation. This breed is affectionate, with a sweet temperament. It can stay still for extended periods, happily lounging in the lap of its loved one. This quality makes the Tiffany an ideal traveling companion, and an ideal house companion for senior citizens and the physically handicapped.",
    temperament: 'Affectionate, Demanding, Interactive, Loyal',
    origin: 'United States',
    life_span: '14 - 16',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 5,
    intelligence: 5,
    health_issues: 1,
    social_needs: 3,
    stranger_friendly: 4
  },
  {
    id: 'cymr',
    image_url: 'Cymric',
    name: 'Cymric',
    description: 'The Cymric is a placid, sweet cat. They do not get too upset about anything that happens in their world. They are loving companions and adore people. They are smart and dexterous, capable of using his paws to get into cabinets or to open doors.',
    temperament: 'Gentle, Loyal, Intelligent, Playful',
    origin: 'Canada',
    life_span: '8 - 14',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 3,
    intelligence: 5,
    health_issues: 3,
    social_needs: 5,
    stranger_friendly: 3
  },
  {
    id: 'cypr',
    image_url: 'Cyprus',
    name: 'Cyprus',
    description: 'Loving, loyal, social and inquisitive, the Cyprus cat forms strong ties with their families and love nothing more than to be involved in everything that goes on in their surroundings. They are not overly active by nature which makes them the perfect companion for people who would like to share their homes with a laid-back relaxed feline companion. ',
    temperament: 'Affectionate, Social',
    origin: 'Cyprus',
    life_span: '12 - 15',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 3,
    intelligence: 3,
    health_issues: 1,
    social_needs: 3,
    stranger_friendly: 4
  },
  {
    id: 'dons',
    image_url: 'Donskoy',
    name: 'Donskoy',
    description: 'Donskoy are affectionate, intelligent, and easy-going. They demand lots of attention and interaction. The Donskoy also gets along well with other pets. It is now thought the same gene that causes degrees of hairlessness in the Donskoy also causes alterations in cat personality, making them calmer the less hair they have.',
    temperament: 'Playful, affectionate, loyal, social',
    origin: 'Russia',
    life_span: '12 - 15',
    adaptability: 4,
    affection_level: 4,
    child_friendly: 3,
    grooming: 2,
    intelligence: 3,
    health_issues: 3,
    social_needs: 5,
    stranger_friendly: 5
  },
  {
    id: 'drex',
    image_url: 'Devon Rex',
    name: 'Devon Rex',
    description: 'The favourite perch of the Devon Rex is right at head level, on the shoulder of her favorite person. She takes a lively interest in everything that is going on and refuses to be left out of any activity. Count on her to stay as close to you as possible, occasionally communicating his opinions in a quiet voice. She loves people and welcomes the attentions of friends and family alike.',
    temperament: 'Highly interactive, Mischievous, Loyal, Social, Playful',
    origin: 'United Kingdom',
    life_span: '10 - 15',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 5,
    health_issues: 3,
    social_needs: 5,
    stranger_friendly: 5
  },
  {
    id: 'ebur',
    image_url: 'European_Burmese',
    name: 'European Burmese',
    description: 'The European Burmese is a very affectionate, intelligent, and loyal cat. They thrive on companionship and will want to be with you, participating in everything you do. While they might pick a favorite family member, chances are that they will interact with everyone in the home, as well as any visitors that come to call. They are inquisitive and playful, even as adults. ',    temperament: 'Sweet, Affectionate, Loyal',
    origin: 'Burma',
    life_span: '10 - 15',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 5,
    health_issues: 4,
    social_needs: 5,
    stranger_friendly: 5
  },
  {
    id: 'emau',
    image_url: 'Egyptian_Mau',
    name: 'Egyptian Mau',
    description: 'The Egyptian Mau is gentle and reserved. She loves her people and desires attention and affection from them but is wary of others. Early, continuing socialization is essential with this sensitive and sometimes shy cat, especially if you plan to show or travel with her. Otherwise, she can be easily startled by unexpected noises or events.',
    temperament: 'Agile, Dependent, Gentle, Intelligent, Lively, Loyal, Playful',
    origin: 'Egypt',
    life_span: '18 - 20',
    adaptability: 2,
    affection_level: 5,
    child_friendly: 3,
    grooming: 1,
    intelligence: 4,
    health_issues: 3,
    social_needs: 4,
    stranger_friendly: 2
  },
  {
    id: 'esho',
    image_url: 'Exotic_Shorthair',
    name: 'Exotic Shorthair',
    description: 'The Exotic Shorthair is a gentle friendly cat that has the same personality as the Persian. They love having fun, don’t mind the company of other cats and dogs, also love to curl up for a sleep in a safe place. Exotics love their own people, but around strangers they are cautious at first. Given time, they usually warm up to visitors.',
    temperament: 'Affectionate, Sweet, Loyal, Quiet, Peaceful',
    origin: 'United States',
    life_span: '12 - 15',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 3,
    grooming: 2,
    intelligence: 3,
    health_issues: 3,
    social_needs: 4,
    stranger_friendly: 2
  },
  {
    id: 'hbro',
    image_url: 'Havana_Brown',
    name: 'Havana Brown',
    description: 'The Havana Brown is human oriented, playful, and curious. She has a strong desire to spend time with her people and involve herself in everything they do. Being naturally inquisitive, the Havana Brown reaches out with a paw to touch and feel when investigating curiosities in its environment. They are truly sensitive by nature and frequently gently touch their human companions as if they are extending a paw of friendship.',
    temperament: 'Affectionate, Curious, Demanding, Friendly, Intelligent, Playful',
    origin: 'United Kingdom',
    life_span: '10 - 15',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 5,
    health_issues: 1,
    social_needs: 5,
    stranger_friendly: 3
  },
  {
    id: 'hima',
    image_url: 'Himalayan',
    name: 'Himalayan',
    description: 'Calm and devoted, Himalayans make excellent companions, though they prefer a quieter home. They are playful in a sedate kind of way and enjoy having an assortment of toys. The Himalayan will stretch out next to you, sleep in your bed and even sit on your lap when she is in the mood.',
    temperament: 'Dependent, Gentle, Intelligent, Quiet, Social',
    origin: 'United States',
    life_span: '9 - 15',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 2,
    grooming: 5,
    intelligence: 3,
    health_issues: 3,
    social_needs: 4,
    stranger_friendly: 2
  },
  {
    id: 'java',
    image_url: 'Javanese',
    name: 'Javanese',
    description: 'Javanese are endlessly interested, intelligent and active. They tend to enjoy jumping to great heights, playing with fishing pole-type or other interactive toys and just generally investigating their surroundings. He will attempt to copy things you do, such as opening doors or drawers.',
    temperament: 'Active, Devoted, Intelligent, Playful',
    origin: 'United States',
    life_span: '10 - 12',
    adaptability: 4,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 5,
    health_issues: 3,
    social_needs: 5,
    stranger_friendly: 3
  },
  {
    id: 'jbob',
    image_url: 'Japanese_Bobtail',
    name: 'Japanese Bobtail',
    description: 'The Japanese Bobtail is an active, sweet, loving and highly intelligent breed. They love to be with people and play seemingly endlessly. They learn their name and respond to it. They bring toys to people and play fetch with a favorite toy for hours. Bobtails are social and are at their best when in the company of people. They take over the house and are not intimidated. If a dog is in the house, Bobtails assume Bobtails are in charge.',
    temperament: 'Active, Agile, Clever, Easy Going, Intelligent, Lively, Loyal, Playful, Social',    origin: 'Japan',
    life_span: '14 - 16',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 5,
    health_issues: 1,
    social_needs: 5,
    stranger_friendly: 5
  },
  {
    id: 'khao',
    image_url: 'Khao_Manee',
    name: 'Khao Manee',
    description: 'The Khao Manee is highly intelligent, with an extrovert and inquisitive nature, however they are also very calm and relaxed, making them an idea lap cat.',
    temperament: 'Calm, Relaxed, Talkative, Playful, Warm',
    origin: 'Thailand',
    life_span: '10 - 12',
    adaptability: 4,
    affection_level: 4,
    child_friendly: 3,
    grooming: 3,
    intelligence: 4,
    health_issues: 1,
    social_needs: 3,
    stranger_friendly: 3
  },
  {
    id: 'kora',
    image_url: 'Korat',
    name: 'Korat',
    description: 'The Korat is a natural breed, and one of the oldest stable cat breeds. They are highly intelligent and confident cats that can be fearless, although they are startled by loud sounds and sudden movements. Korats form strong bonds with their people and like to cuddle and stay nearby.',
    temperament: 'Active, Loyal, highly intelligent, Expressive, Trainable',
    origin: 'Thailand',
    life_span: '10 - 15',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 5,
    health_issues: 1,
    social_needs: 5,
    stranger_friendly: 2
  },
  {
    id: 'kuri',
    image_url: 'Kurilian',
    name: 'Kurilian',
    description: 'The character of the Kurilian Bobtail is independent, highly intelligent, clever, inquisitive, sociable, playful, trainable, absent of aggression and very gentle. They are devoted to their humans and when allowed are either on the lap of or sleeping in bed with their owners.',
    temperament: 'Independent, highly intelligent, clever, inquisitive, sociable, playful, trainable',
    origin: 'Russia',
    life_span: '15 - 20',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 5,
    grooming: 1,
    intelligence: 5,
    health_issues: 1,
    social_needs: 5,
    stranger_friendly: 5
  },
  {
    id: 'lape',
    image_url: 'LaPerm',
    name: 'LaPerm',
    description: 'LaPerms are gentle and affectionate but also very active. Unlike many active breeds, the LaPerm is also quite content to be a lap cat. The LaPerm will often follow your lead; that is, if they are busy playing and yo udecide to sit and relax, simply pick up your LaPerm and sit down with it, and it will stay in your lap, devouring the attention you give it.',
    temperament: 'Affectionate, Friendly, Gentle, Intelligent, Playful, Quiet',
    origin: 'Thailand',
    life_span: '10 - 15',
    adaptability: 5,
    affection_level: 5,
    child_friendly: 4,
    grooming: 1,
    intelligence: 5,
    health_issues: 1,
    social_needs: 4,
    stranger_friendly: 4
  },
  {
    id: 'lihu',
    image_url: 'Dragon_Li',
    name: 'Dragon Li',
    description: "The Dragon Li is loyal, but not particularly affectionate. They are known to be very intelligent, and their natural breed status means that they're very active. She is is gentle with people, and has a reputation as a talented hunter of rats and other vermin.",
    temperament: 'Intelligent, Friendly, Gentle, Loving, Loyal',
    origin: 'China',
    life_span: '12 - 15',
    adaptability: 3,
    affection_level: 3,
    child_friendly: 3,
    grooming: 1,
    intelligence: 3,
    health_issues: 1,
    social_needs: 4,
    stranger_friendly: 3
  }
]